-- ============================================================================
-- Special Class TOTP Session Trigger & Cron Setup
-- ============================================================================
-- Purpose:
--   1. When a special class is created in lecture_sessions (is_special_class = TRUE),
--      automatically insert a TOTP session entry
--   2. If special class is created for the same day, insert immediately
--   3. Use cron job to ensure TOTP sessions exist at 00:00 daily for any
--      special classes scheduled for that day that don't have sessions yet
--
-- Tables Modified: totp_sessions (INSERT)
-- Functions Created:
--   - public.generate_totp_code() - generates random 6-digit code
--   - public.handle_special_class_totp_creation() - trigger function
-- Triggers Created:
--   - trigger_special_class_totp_on_insert (AFTER INSERT on lecture_sessions)
-- Cron Jobs Created:
--   - special_class_totp_daily_populate (runs daily at 00:00)
--
-- Safety: Safe to run multiple times (uses CREATE OR REPLACE, IF NOT EXISTS)
-- ============================================================================

BEGIN;

-- ============================================================================
-- Step 1: Create TOTP Code Generator Function (if not exists)
-- ============================================================================
CREATE OR REPLACE FUNCTION public.generate_totp_code()
RETURNS VARCHAR AS $$
BEGIN
  RETURN LPAD(FLOOR(RANDOM() * 1000000)::INTEGER::TEXT, 6, '0');
END;
$$ LANGUAGE plpgsql VOLATILE;

COMMENT ON FUNCTION public.generate_totp_code() IS 'Generates a random 6-digit TOTP code for attendance verification';

-- ============================================================================
-- Step 2: Create Function for Special Class TOTP Creation
-- ============================================================================
-- This function:
--   1. Is called when a special class is inserted
--   2. Creates TOTP session entry automatically
--   3. Sets expiry to 60 seconds from creation (for dynamic mode)
--   4. Logs each creation for debugging
--   5. Uses SECURITY DEFINER to bypass RLS policies
-- ============================================================================
CREATE OR REPLACE FUNCTION public.handle_special_class_totp_creation()
RETURNS TRIGGER
SECURITY DEFINER
AS $$
DECLARE
  v_totp_id UUID;
  v_code VARCHAR(6);
  v_session_date DATE;
  v_log_msg TEXT;
BEGIN
  -- Only process if this is a special class
  IF NEW.is_special_class = FALSE OR NEW.is_special_class IS NULL THEN
    RETURN NEW;
  END IF;

  -- Only process if the lecture session is active (not cancelled/inactive)
  IF NEW.is_active = FALSE OR NEW.is_cancelled = TRUE THEN
    RETURN NEW;
  END IF;

  -- Check if TOTP session already exists (shouldn't happen, but safety check)
  IF EXISTS (
    SELECT 1 FROM public.totp_sessions
    WHERE lecture_session_id = NEW.id
  ) THEN
    RAISE NOTICE '[TOTP Trigger] TOTP session already exists for special class %', NEW.id;
    RETURN NEW;
  END IF;

  BEGIN
    -- Generate TOTP code
    v_code := public.generate_totp_code();
    v_session_date := NEW.session_date::DATE;

    -- Insert TOTP session
    INSERT INTO public.totp_sessions (
      id,
      university_id,
      lecture_session_id,
      code,
      totp_mode,
      generated_at,
      expires_at,
      code_shared,
      attendance_marking_enabled,
      created_at,
      updated_at
    ) VALUES (
      gen_random_uuid(),
      NEW.university_id,
      NEW.id,
      v_code,
      'autogenerated_dynamic'::VARCHAR,
      NOW(),
      NOW() + INTERVAL '60 seconds',  -- Dynamic codes expire in 60 seconds (minimum 1 min for cron)
      FALSE,                           -- Initially not shared with students
      FALSE,                           -- Initially students cannot mark
      NOW(),
      NOW()
    );

    -- Log creation
    v_log_msg := FORMAT(
      '[TOTP Trigger - Special Class] Created TOTP for special class ID=%s, Course=%s, Date=%s, Time=%s-%s, Code=%s',
      NEW.id,
      NEW.course_id,
      v_session_date,
      NEW.start_time,
      NEW.end_time,
      v_code
    );
    RAISE NOTICE '%', v_log_msg;

  EXCEPTION 
    WHEN unique_violation THEN
      -- If unique constraint violated (shouldn't happen with gen_random_uuid), log and continue
      RAISE WARNING '[TOTP Trigger] Unique violation for lecture session %s - TOTP may already exist', NEW.id;
    WHEN OTHERS THEN
      -- Log error but don't fail the insert
      RAISE WARNING '[TOTP Trigger] Error creating TOTP for special class %s: %s', NEW.id, SQLERRM;
  END;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.handle_special_class_totp_creation() IS 
  'Trigger function that automatically creates TOTP session when a special class is created. Called on INSERT to lecture_sessions.';

-- ============================================================================
-- Step 3: Drop existing trigger if it exists (safe cleanup)
-- ============================================================================
DROP TRIGGER IF EXISTS trigger_special_class_totp_on_insert ON public.lecture_sessions;

-- ============================================================================
-- Step 4: Create Trigger on lecture_sessions INSERT
-- ============================================================================
-- This trigger fires AFTER INSERT on lecture_sessions
-- It only processes rows where is_special_class = TRUE
-- ============================================================================
CREATE TRIGGER trigger_special_class_totp_on_insert
AFTER INSERT ON public.lecture_sessions
FOR EACH ROW
EXECUTE FUNCTION public.handle_special_class_totp_creation();

COMMENT ON TRIGGER trigger_special_class_totp_on_insert ON public.lecture_sessions IS 
  'Automatically creates TOTP session when a special class is inserted into lecture_sessions';

-- ============================================================================
-- Step 5: Create Daily Cron Function for Special Classes
-- ============================================================================
-- This function:
--   1. Runs daily at 00:00 (midnight)
--   2. Finds all special classes scheduled for TODAY
--   3. Creates TOTP sessions for those that don't have one yet
--   4. Reports creation statistics
--
-- Why needed:
--   - Ensures TOTP exists even if trigger fails
--   - Handles edge cases (updates, cascades)
--   - Provides daily reconciliation
-- ============================================================================
CREATE OR REPLACE FUNCTION public.populate_totp_for_special_classes_today()
RETURNS TABLE(
  created_count INTEGER,
  already_exist_count INTEGER,
  total_special_classes INTEGER,
  message TEXT,
  timestamp_utc TIMESTAMP WITH TIME ZONE
) AS $$
DECLARE
  v_created_count INTEGER := 0;
  v_already_exist_count INTEGER := 0;
  v_total_count INTEGER := 0;
  v_today_date DATE;
  v_lecture_session_id UUID;
  v_university_id UUID;
  v_code VARCHAR(6);
BEGIN
  v_today_date := CURRENT_DATE;

  -- Get count of today's special classes that are active
  SELECT COUNT(*) INTO v_total_count
  FROM public.lecture_sessions
  WHERE session_date::DATE = v_today_date
  AND is_special_class = TRUE
  AND is_active = TRUE
  AND is_cancelled = FALSE;

  -- Loop through special classes for today that don't have TOTP sessions
  FOR v_lecture_session_id, v_university_id IN
    SELECT ls.id, ls.university_id
    FROM public.lecture_sessions ls
    WHERE ls.session_date::DATE = v_today_date
    AND ls.is_special_class = TRUE
    AND ls.is_active = TRUE
    AND ls.is_cancelled = FALSE
    AND NOT EXISTS (
      SELECT 1 FROM public.totp_sessions ts
      WHERE ts.lecture_session_id = ls.id
    )
  LOOP
    BEGIN
      -- Generate TOTP code
      v_code := public.generate_totp_code();

      -- Insert TOTP session
      INSERT INTO public.totp_sessions (
        id,
        university_id,
        lecture_session_id,
        code,
        totp_mode,
        generated_at,
        expires_at,
        code_shared,
        attendance_marking_enabled,
        created_at,
        updated_at
      ) VALUES (
        gen_random_uuid(),
        v_university_id,
        v_lecture_session_id,
        v_code,
        'autogenerated_dynamic'::VARCHAR,
        NOW(),
        NOW() + INTERVAL '60 seconds',  -- Minimum 60 seconds (1 minute) for cron job capability
        FALSE,
        FALSE,
        NOW(),
        NOW()
      );

      v_created_count := v_created_count + 1;

    EXCEPTION 
      WHEN unique_violation THEN
        -- Record already exists
        v_already_exist_count := v_already_exist_count + 1;
      WHEN OTHERS THEN
        -- Log error and continue
        RAISE WARNING '[Cron: Special Classes TOTP] Error for session %s: %s', v_lecture_session_id, SQLERRM;
    END;
  END LOOP;

  -- Return results
  RETURN QUERY SELECT 
    v_created_count,
    v_already_exist_count,
    v_total_count,
    FORMAT(
      'Daily TOTP Population for Special Classes | Date: %s | Created: %s, Already Exist: %s, Total Special Classes: %s',
      v_today_date::TEXT,
      v_created_count,
      v_already_exist_count,
      v_total_count
    )::TEXT,
    NOW();  -- NOW() already returns TIMESTAMP WITH TIME ZONE

END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.populate_totp_for_special_classes_today() IS 
  'Daily cron function that ensures TOTP sessions exist for all special classes scheduled for today. Should run at 00:00 daily.';

-- ============================================================================
-- Step 6: Create Cron Extension and Schedule Daily Job
-- ============================================================================
-- Note: This requires pg_cron to be enabled in Supabase
-- If it's not enabled, ask Supabase support to enable pg_cron extension
-- Once enabled, uncomment the following lines to schedule the cron job
-- ============================================================================

-- First, enable pg_cron extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Schedule the daily population job
-- This runs every day at 00:00 UTC (midnight UTC)
-- First unschedule if it already exists, then schedule the new one
DO $$
BEGIN
  PERFORM cron.unschedule('special_classes_populate_totp_daily');
EXCEPTION WHEN OTHERS THEN
  -- Job doesn't exist yet, which is fine
END;
$$;

SELECT cron.schedule(
  'special_classes_populate_totp_daily',
  '*/1 * * * *',  -- Every 1 minute (minimum cron capability)
  'SELECT public.populate_totp_for_special_classes_today();'
);

-- ============================================================================
-- Step 7: Alternative Cron Based on Timezone
-- ============================================================================
-- If you want to run at a different time (e.g., IST which is UTC+5:30),
-- adjust the cron expression. For IST 00:00 = UTC 18:30 previous day
-- Uncomment below if you prefer IST-based scheduling:
-- ============================================================================

-- For 05:30 UTC (11:00 IST):
-- DO $$
-- BEGIN
--   PERFORM cron.unschedule('special_classes_populate_totp_ist_morning');
-- EXCEPTION WHEN OTHERS THEN
--   -- Job doesn't exist yet, which is fine
-- END;
-- $$;
-- 
-- SELECT cron.schedule(
--   'special_classes_populate_totp_ist_morning',
--   '30 5 * * *',  -- Daily at 05:30 UTC = 11:00 IST
--   'SELECT public.populate_totp_for_special_classes_today();'
-- );

-- ============================================================================
-- Step 8: View Cron Jobs (optional - for monitoring)
-- ============================================================================
-- Run these queries to check if cron job is scheduled:
-- SELECT * FROM cron.job;
-- SELECT * FROM cron.job_run_details WHERE jobname LIKE '%special%' ORDER BY start_time DESC LIMIT 10;

-- ============================================================================
-- Step 9: Manual Testing & Execution
-- ============================================================================
-- To manually test this setup, run:
--
-- 1. Test the TOTP code generator:
--    SELECT public.generate_totp_code();
--
-- 2. Manually run the cron function to see results:
--    SELECT * FROM public.populate_totp_for_special_classes_today();
--
-- 3. Create a test special class and verify TOTP is created:
--    INSERT INTO public.lecture_sessions (
--      university_id, course_id, section_id, room_id, session_date,
--      start_time, end_time, is_special_class, is_active
--    ) VALUES (
--      'your-university-id', 'your-course-id', 'your-section-id', 'your-room-id',
--      CURRENT_DATE, '10:00'::time, '11:00'::time, TRUE, TRUE
--    );
--    -- Then check if TOTP was created:
--    SELECT * FROM public.totp_sessions WHERE created_at > NOW() - INTERVAL '1 minute';
--
-- 4. View all special classes without TOTP sessions:
--    SELECT ls.id, ls.course_id, ls.session_date, ls.start_time, ls.end_time
--    FROM public.lecture_sessions ls
--    LEFT JOIN public.totp_sessions ts ON ts.lecture_session_id = ls.id
--    WHERE ls.is_special_class = TRUE AND ts.id IS NULL
--    ORDER BY ls.session_date DESC;
--
-- 5. View recent cron job execution:
--    SELECT * FROM cron.job_run_details 
--    WHERE jobname LIKE '%special%' 
--    ORDER BY start_time DESC LIMIT 5;

-- ============================================================================
-- Step 10: Log Messages & Monitoring
-- ============================================================================
-- All operations log to PostgreSQL logs with format [Component] Message
-- To view recent logs:
--   SELECT * FROM pg_read_file('pg_log/postgresql-*.log') LIMIT 100;
--
-- In Supabase, check the "Database Logs" section in the dashboard
-- Look for messages with prefixes:
--   [TOTP Trigger] - From INSERT trigger
--   [Cron: Special Classes TOTP] - From cron job
--   [TOTP Trigger - Special Class] - Successful creation notice
--

COMMIT;

-- ============================================================================
-- EXECUTION SUMMARY
-- ============================================================================
-- This script creates:
--
-- ✓ Function: public.generate_totp_code()
--   - Generates random 6-digit codes
--   - Called by trigger and cron
--
-- ✓ Function: public.handle_special_class_totp_creation()
--   - Trigger function for INSERT operations
--   - Validates special class and creates TOTP
--   - Includes error handling and logging
--
-- ✓ Trigger: trigger_special_class_totp_on_insert
--   - Fires AFTER INSERT on lecture_sessions
--   - Only processes is_special_class = TRUE
--   - Executes immediately when class created
--
-- ✓ Function: public.populate_totp_for_special_classes_today()
--   - Daily reconciliation function
--   - Creates missing TOTP sessions
--   - Returns statistics and message
--
-- ✓ Cron Job: special_classes_populate_totp_daily
--   - Scheduled daily at 00:00 UTC
--   - Can be modified in Step 6
--   - Provides safety net if trigger fails
--
-- ============================================================================
-- NEXT STEPS
-- ============================================================================
-- 1. Run this script in your Supabase SQL Editor
-- 2. Verify: SELECT * FROM cron.job WHERE jobname LIKE '%special%';
-- 3. Test: Create a special class and verify TOTP is auto-created
-- 4. Monitor: Watch database logs for [TOTP Trigger] messages
-- 5. Verify daily: Check cron job runs at scheduled time
--
-- ============================================================================
