-- ============================================================================
-- TOTP Session Population Function & Manual Trigger Script
-- ============================================================================
-- Use this script to manually populate totp_sessions for today's lecture_sessions
-- when new sessions have been added to the timetable
-- ============================================================================

-- Step 1: Function to generate random TOTP code (6 digits)
CREATE OR REPLACE FUNCTION public.generate_totp_code()
RETURNS VARCHAR AS $$
BEGIN
  RETURN LPAD(FLOOR(RANDOM() * 1000000)::INTEGER::TEXT, 6, '0');
END;
$$ LANGUAGE plpgsql;

-- Step 2: Function to populate totp_sessions for today's lecture_sessions
CREATE OR REPLACE FUNCTION public.populate_totp_for_today()
RETURNS TABLE(
  created_count INTEGER,
  skipped_count INTEGER,
  total_count INTEGER,
  message TEXT
) AS $$
DECLARE
  v_created_count INTEGER := 0;
  v_skipped_count INTEGER := 0;
  v_total_count INTEGER := 0;
  v_today_date DATE := CURRENT_DATE;
  v_lecture_session_id UUID;
  v_university_id UUID;
BEGIN
  -- Get count of today's lecture sessions
  SELECT COUNT(*) INTO v_total_count
  FROM public.lecture_sessions
  WHERE session_date::DATE = v_today_date
  AND is_active = TRUE;

  -- Loop through all today's lecture sessions that don't have TOTP sessions
  FOR v_lecture_session_id, v_university_id IN
    SELECT ls.id, ls.university_id
    FROM public.lecture_sessions ls
    WHERE ls.session_date::DATE = v_today_date
    AND ls.is_active = TRUE
    AND NOT EXISTS (
      SELECT 1 FROM public.totp_sessions ts
      WHERE ts.lecture_session_id = ls.id
    )
  LOOP
    BEGIN
      INSERT INTO public.totp_sessions (
        lecture_session_id,
        university_id,
        code,
        totp_mode,
        created_at,
        expires_at,
        code_shared,
        attendance_marking_enabled
      ) VALUES (
        v_lecture_session_id,
        v_university_id,
        public.generate_totp_code(),
        'autogenerated_dynamic'::VARCHAR,
        NOW(),
        NOW() + INTERVAL '30 seconds',  -- Dynamic codes expire in 30 seconds
        FALSE,  -- Initially not shared with students
        FALSE   -- Initially students cannot mark
      );
      
      v_created_count := v_created_count + 1;
    EXCEPTION WHEN unique_violation THEN
      v_skipped_count := v_skipped_count + 1;
    END;
  END LOOP;

  RETURN QUERY SELECT 
    v_created_count,
    v_skipped_count,
    v_total_count,
    FORMAT('Created: %s, Skipped (already exist): %s, Total sessions today: %s', 
           v_created_count, v_skipped_count, v_total_count)::TEXT;
END;
$$ LANGUAGE plpgsql;

-- Step 3: Function to populate TOTP sessions for a specific date
CREATE OR REPLACE FUNCTION public.populate_totp_for_date(p_date DATE)
RETURNS TABLE(
  created_count INTEGER,
  skipped_count INTEGER,
  total_count INTEGER,
  message TEXT
) AS $$
DECLARE
  v_created_count INTEGER := 0;
  v_skipped_count INTEGER := 0;
  v_total_count INTEGER := 0;
  v_lecture_session_id UUID;
  v_university_id UUID;
BEGIN
  -- Get count of lecture sessions for the specified date
  SELECT COUNT(*) INTO v_total_count
  FROM public.lecture_sessions
  WHERE session_date::DATE = p_date
  AND is_active = TRUE;

  -- Loop through all lecture sessions for the date that don't have TOTP sessions
  FOR v_lecture_session_id, v_university_id IN
    SELECT ls.id, ls.university_id
    FROM public.lecture_sessions ls
    WHERE ls.session_date::DATE = p_date
    AND ls.is_active = TRUE
    AND NOT EXISTS (
      SELECT 1 FROM public.totp_sessions ts
      WHERE ts.lecture_session_id = ls.id
    )
  LOOP
    BEGIN
      INSERT INTO public.totp_sessions (
        lecture_session_id,
        university_id,
        code,
        totp_mode,
        created_at,
        expires_at,
        code_shared,
        attendance_marking_enabled
      ) VALUES (
        v_lecture_session_id,
        v_university_id,
        public.generate_totp_code(),
        'autogenerated_dynamic'::VARCHAR,
        NOW(),
        NOW() + INTERVAL '30 seconds',
        FALSE,
        FALSE
      );
      
      v_created_count := v_created_count + 1;
    EXCEPTION WHEN unique_violation THEN
      v_skipped_count := v_skipped_count + 1;
    END;
  END LOOP;

  RETURN QUERY SELECT 
    v_created_count,
    v_skipped_count,
    v_total_count,
    FORMAT('Date: %s | Created: %s, Skipped: %s, Total: %s', 
           p_date::TEXT, v_created_count, v_skipped_count, v_total_count)::TEXT;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- MANUAL TRIGGER SCRIPTS (Run these when needed)
-- ============================================================================

-- RUN THIS to populate TOTP sessions for TODAY:
-- SELECT * FROM public.populate_totp_for_today();

-- RUN THIS to populate TOTP sessions for a specific date (replace '2026-02-26'):
-- SELECT * FROM public.populate_totp_for_date('2026-02-26'::DATE);

-- VIEW RESULTS:
-- Check if TOTP sessions were created for today:
-- SELECT 
--   ls.id,
--   ls.session_date,
--   c.code as course_code,
--   c.name as course_name,
--   COALESCE(ts.code, 'NO TOTP CODE') as totp_code,
--   ts.code_shared,
--   ts.attendance_marking_enabled
-- FROM public.lecture_sessions ls
-- LEFT JOIN public.totp_sessions ts ON ts.lecture_session_id = ls.id
-- LEFT JOIN public.courses c ON ls.course_id = c.id
-- WHERE ls.session_date::DATE = CURRENT_DATE
-- AND ls.is_active = TRUE
-- ORDER BY ls.session_date, ls.start_time;

-- ============================================================================
-- AUTO-TRIGGER (Optional: Create daily job to auto-populate)
-- ============================================================================
-- This creates a cron job in Supabase to auto-populate TOTP sessions daily at 00:05 UTC
-- 
-- NOTE: Requires pg_cron extension to be enabled in Supabase
-- Ask Supabase support to enable it if needed
--
-- CREATE EXTENSION IF NOT EXISTS pg_cron;
-- 
-- SELECT cron.schedule(
--   'populate_totp_daily',
--   '5 0 * * *',  -- 00:05 UTC daily
--   'SELECT public.populate_totp_for_today();'
-- );
--
-- To view scheduled jobs:
-- SELECT * FROM cron.job;
--
-- To unschedule:
-- SELECT cron.unschedule('populate_totp_daily');

-- ============================================================================
-- VERIFY FUNCTIONS EXIST
-- ============================================================================
-- SELECT routine_name, routine_type
-- FROM information_schema.routines
-- WHERE routine_schema = 'public'
-- AND routine_name LIKE '%populate_totp%'
-- OR routine_name LIKE '%generate_totp%'
-- ORDER BY routine_name;
