import supabase from '@/lib/supabase';

/**
 * Cache for schedule data
 */
interface CacheEntry {
  data: LectureSessionExtended[];
  timestamp: number;
}

const scheduleCache: Map<string, CacheEntry> = new Map();
const CACHE_DURATION = 5 * 60 * 1000; // 5 minutes

/**
 * Semester date cache
 */
interface SemesterDateEntry {
  startDate: string;
  endDate: string;
  timestamp: number;
}

const semesterDateCache: Map<string, SemesterDateEntry> = new Map();
const SEMESTER_CACHE_DURATION = 24 * 60 * 60 * 1000; // 24 hours

/**
 * Fetch semester start and end dates
 * @param semesterId - Semester ID
 * @returns Object with startDate and endDate (YYYY-MM-DD format) or null
 */
export async function getSemesterDates(
  semesterId: string
): Promise<{ startDate: string; endDate: string } | null> {
  try {
    // Check cache first
    const cached = semesterDateCache.get(semesterId);
    if (cached && Date.now() - cached.timestamp < SEMESTER_CACHE_DURATION) {
      console.log('[Schedule Service] ✓ Semester dates from cache');
      return { startDate: cached.startDate, endDate: cached.endDate };
    }

    console.log('[Schedule Service] 📚 Fetching semester dates for:', semesterId.substring(0, 8) + '...');
    
    const { data, error } = await supabase
      .from('semesters')
      .select('start_date, end_date')
      .eq('id', semesterId)
      .single();

    if (error) {
      console.error('[Schedule Service] Error fetching semester dates:', error);
      return null;
    }

    const result = {
      startDate: data.start_date,
      endDate: data.end_date,
    };

    // Cache the result
    semesterDateCache.set(semesterId, {
      ...result,
      timestamp: Date.now(),
    });

    console.log('[Schedule Service] ✓ Semester date range:', result.startDate, 'to', result.endDate);
    return result;
  } catch (error) {
    console.error('[Schedule Service] Exception in getSemesterDates:', error);
    return null;
  }
}

/**
 * Lecture Session from database
 */
export interface LectureSession {
  id: string;
  university_id: string;
  timetable_id: string | null;
  course_id: string;
  section_id: string;
  room_id: string | null;
  instructor_ids: string[];
  session_date: string; // YYYY-MM-DD
  scheduled_start_time: string | null; // HH:mm:ss
  scheduled_end_time: string | null; // HH:mm:ss
  start_time: string; // HH:mm:ss
  end_time: string; // HH:mm:ss
  actual_start_time: string | null; // HH:mm:ss
  actual_end_time: string | null; // HH:mm:ss
  totp_required: boolean;
  session_status: 'scheduled' | 'active' | 'completed' | 'cancelled' | 'rescheduled';
  is_special_class: boolean;
  max_late_minutes: number;
  attendance_open: boolean;
  attendance_close_time: string | null;
  is_active: boolean;
  is_cancelled: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Extended lecture session with course and room details
 */
export interface LectureSessionExtended extends LectureSession {
  course?: {
    id: string;
    code: string;
    name: string;
  };
  room?: {
    id: string;
    room_number: string;
    room_name: string;
    building?: {
      id: string;
      name?: string;
    };
  };
  instructors?: Array<{
    id: string;
    name: string;
  }>;
  displayStatus?: 'completed' | 'ongoing' | 'upcoming';
}

/**
 * TOTP Session data
 */
export interface TOTPSession {
  id: string;
  university_id: string;
  lecture_session_id: string;
  code: string;
  totp_mode: 'autogenerated_dynamic' | 'autogenerated_static' | 'manual';
  generated_at: string;
  expires_at: string;
  last_refresh_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Calculate display status for a session based on current time
 * Returns 'completed', 'ongoing', or 'upcoming'
 * @param session - Lecture session with date and time info
 * @returns Display status
 */
export function calculateSessionDisplayStatus(
  session: LectureSession
): 'completed' | 'ongoing' | 'upcoming' {
  const now = new Date();
  const today = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`; // local IST date, not UTC
  const currentTimeStr = now.toTimeString().substring(0, 8); // HH:mm:ss — already local time

  // Session is in the past → completed
  if (session.session_date < today) {
    return 'completed';
  }

  // Session is in the future → upcoming
  if (session.session_date > today) {
    return 'upcoming';
  }

  // Session is today → check time
  // Get the end time (prefer actual_end_time if it exists)
  const endTime = session.actual_end_time || session.end_time || session.scheduled_end_time;
  const startTime = session.scheduled_start_time || session.start_time;

  if (!endTime || !startTime) {
    // If times are not available, assume upcoming
    return 'upcoming';
  }

  // If current time is past end time → completed
  if (currentTimeStr > endTime) {
    return 'completed';
  }

  // If current time is before start time → upcoming
  if (currentTimeStr < startTime) {
    return 'upcoming';
  }

  // Otherwise → ongoing
  return 'ongoing';
}

/**
 * Fetch lecture sessions for a student
 * Filters by: university_id → student enrollments → section_id → lecture sessions
 * @param studentId - Student user ID
 * @param universityId - University ID
 * @param startDate - Start date (YYYY-MM-DD)
 * @param endDate - End date (YYYY-MM-DD)
 */
export async function getStudentSchedule(
  studentId: string,
  universityId: string,
  startDate: string,
  endDate: string
): Promise<{ sessions: LectureSessionExtended[] | null; error: Error | null }> {
  try {
    // Check cache first
    const cacheKey = `${studentId}-${startDate}-${endDate}`;
    const cached = scheduleCache.get(cacheKey);
    if (cached && Date.now() - cached.timestamp < CACHE_DURATION) {
      console.log('[Schedule Service] ✓ Schedule data from cache');
      return { sessions: cached.data, error: null };
    }

    console.log(
      `[Schedule Service] ========================================`
    );
    console.log(
      `[Schedule Service] 🔍 QUERY PARAMETERS:`
    );
    console.log(
      `[Schedule Service]   - studentId: ${studentId}`
    );
    console.log(
      `[Schedule Service]   - universityId: ${universityId}`
    );
    console.log(
      `[Schedule Service]   - dateRange: ${startDate} to ${endDate}`
    );
    console.log(
      `[Schedule Service] ========================================`
    );

    // Step 1: Get student enrollments with section details
    console.log(
      `[Schedule Service] STEP 1: Querying student_enrollments...`
    );
    const { data: enrollments, error: enrollmentError } = await supabase
      .from('student_enrollments')
      .select('section_id, batch')
      .eq('user_id', studentId)
      .eq('university_id', universityId)
      .eq('is_active', true);

    if (enrollmentError) throw enrollmentError;

    console.log(
      `[Schedule Service]   ✓ Query result: Found ${enrollments?.length || 0} enrollments`
    );
    if (enrollments && enrollments.length > 0) {
      console.log(
        `[Schedule Service]   Sample enrollments (first 2): ${JSON.stringify(
          enrollments.slice(0, 2),
          null,
          2
        )}`
      );
    } else {
      console.warn(
        `[Schedule Service]   ⚠️  NO ENROLLMENTS FOUND - Student may not be enrolled in any sections`
      );
    }

    if (!enrollments || enrollments.length === 0) {
      console.warn('[Schedule Service] No active enrollments found for student');
      return { sessions: [] as LectureSessionExtended[], error: null };
    }

    const sectionIds = enrollments.map((e) => e.section_id);

    // Step 2: Get lecture sessions for those sections
    console.log(
      `[Schedule Service] STEP 2: Querying lecture_sessions for ${sectionIds.length} section(s)...`
    );
    console.log(
      `[Schedule Service]   sectionIds: [${sectionIds.map((id) => id.substring(0, 8)).join(', ')}...]`
    );
    const { data: sessions, error: sessionsError } = await supabase
      .from('lecture_sessions')
      .select(
        `
        id,
        university_id,
        timetable_id,
        course_id,
        section_id,
        room_id,
        instructor_ids,
        session_date,
        scheduled_start_time,
        scheduled_end_time,
        start_time,
        end_time,
        actual_start_time,
        actual_end_time,
        totp_required,
        session_status,
        is_special_class,
        max_late_minutes,
        attendance_open,
        attendance_close_time,
        is_active,
        is_cancelled,
        created_at,
        updated_at,
        courses(id, code, name),
        rooms(id, room_number, room_name, building:buildings(id, name))
      `
      )
      .in('section_id', sectionIds)
      .eq('university_id', universityId)
      .eq('is_active', true)
      .eq('is_cancelled', false)
      .gte('session_date', startDate)
      .lte('session_date', endDate)
      .order('session_date', { ascending: true })
      .order('start_time', { ascending: true });

    if (sessionsError) throw sessionsError;

    console.log(
      `[Schedule Service]   ✓ Query result: Found ${sessions?.length || 0} lecture sessions`
    );
    if (sessions && sessions.length > 0) {
      console.log(
        `[Schedule Service]   Sample sessions (first 2): ${JSON.stringify(
          sessions.slice(0, 2).map((s: any) => ({
            id: s.id,
            course: s.courses?.name,
            code: s.courses?.code,
            date: s.session_date,
            time: `${s.start_time} - ${s.end_time}`,
            room: s.rooms?.room_name || s.rooms?.room_number,
            building: s.rooms?.building?.name,
            status: s.session_status,
            instructorIds: s.instructor_ids?.length || 0,
          })),
          null,
          2
        )}`
      );
    } else {
      console.warn(
        `[Schedule Service]   ⚠️  NO SESSIONS FOUND - Check if sections have lecture_sessions in the database for the date range`
      );
    }

    // Step 3: Fetch instructor names for instructor_ids array
    console.log('[Schedule Service] STEP 3: Enriching sessions with instructor details...');
    const extendedSessions = await Promise.all(
      (sessions || []).map(async (session: any, idx: number) => {
        let instructors: Array<{ id: string; name: string }> | undefined;

        if (session.instructor_ids && session.instructor_ids.length > 0) {
          if (idx === 0) {
            console.log(
              `[Schedule Service]   Fetching instructors for sessions...`
            );
          }
          const { data: instructorData, error: instructorError } = await supabase
            .from('instructors')
            .select('id, name')
            .in('id', session.instructor_ids);

          if (instructorError) {
            console.warn(
              `[Schedule Service] Error fetching instructors for session ${session.id}:`,
              instructorError
            );
          }

          instructors = instructorData || [];
        }

        const extendedSession = {
          ...session,
          instructors,
          course: session.courses,
          room: session.rooms,
          displayStatus: calculateSessionDisplayStatus(session),
        };

        return extendedSession;
      })
    );

    console.log(`[Schedule Service] ✓ Retrieved ${extendedSessions.length} sessions with displayStatus`);

    // Cache the result
    scheduleCache.set(cacheKey, {
      data: extendedSessions as LectureSessionExtended[],
      timestamp: Date.now(),
    });

    return { sessions: extendedSessions as LectureSessionExtended[], error: null };
  } catch (error) {
    console.error('[Schedule Service] ❌ Error fetching student schedule:', error);
    console.log(
      `[Schedule Service] ========================================`
    );
    return { sessions: null, error: error as Error };
  }
}

export async function getTeacherSchedule(
  instructorId: string,
  universityId: string,
  startDate: string,
  endDate: string
): Promise<{ sessions: LectureSessionExtended[] | null; error: Error | null }> {
  try {
    // Check cache first
    const cacheKey = `teacher-${instructorId}-${startDate}-${endDate}`;
    const cached = scheduleCache.get(cacheKey);
    if (cached && Date.now() - cached.timestamp < CACHE_DURATION) {
      console.log('[Schedule Service] ✓ Teacher schedule data from cache');
      return { sessions: cached.data, error: null };
    }

    console.log(
      `[Schedule Service] ========================================`
    );
    console.log(
      `[Schedule Service] 🔍 TEACHER SCHEDULE QUERY PARAMETERS:`
    );
    console.log(
      `[Schedule Service]   - instructorId: ${instructorId}`
    );
    console.log(
      `[Schedule Service]   - universityId: ${universityId}`
    );
    console.log(
      `[Schedule Service]   - dateRange: ${startDate} to ${endDate}`
    );
    console.log(
      `[Schedule Service] ========================================`
    );

    // Step 1: Get lecture sessions for this university in the date range
    console.log(
      `[Schedule Service] STEP 1: Querying lecture_sessions for instructor...`
    );
    console.log(
      `[Schedule Service]   Query: SELECT * FROM lecture_sessions WHERE university_id = '${universityId}' AND is_active = true AND is_cancelled = false AND session_date BETWEEN '${startDate}' AND '${endDate}'`
    );
    
    const { data: sessions, error: sessionsError } = await supabase
      .from('lecture_sessions')
      .select(
        `
        id,
        university_id,
        timetable_id,
        course_id,
        section_id,
        room_id,
        instructor_ids,
        session_date,
        scheduled_start_time,
        scheduled_end_time,
        start_time,
        end_time,
        actual_start_time,
        actual_end_time,
        totp_required,
        session_status,
        is_special_class,
        max_late_minutes,
        attendance_open,
        attendance_close_time,
        is_active,
        is_cancelled,
        created_at,
        updated_at,
        courses(id, code, name),
        rooms(id, room_number, room_name, building:buildings(id, name))
      `
      )
      .eq('university_id', universityId)
      .eq('is_active', true)
      .eq('is_cancelled', false)
      .gte('session_date', startDate)
      .lte('session_date', endDate)
      .order('session_date', { ascending: true })
      .order('start_time', { ascending: true });

    if (sessionsError) {
      console.error(
        `[Schedule Service] ❌ CRITICAL: Query error! This is likely an RLS policy issue.`,
        sessionsError
      );
      console.error('[Schedule Service] Error details:', {
        message: sessionsError.message,
        code: sessionsError.code,
        hint: sessionsError.hint,
      });
      throw sessionsError;
    }

    console.log(
      `[Schedule Service]   ✓ Query result: Found ${sessions?.length || 0} total lecture sessions`
    );

    if (!sessions || sessions.length === 0) {
      console.warn('[Schedule Service]   ⚠️ No sessions returned from database!');
      console.warn('[Schedule Service]   Possible causes:');
      console.warn('[Schedule Service]     1. RLS policy blocks read access to lecture_sessions');
      console.warn('[Schedule Service]     2. No lecture_sessions exist for this university/date range');
      console.warn('[Schedule Service]     3. All sessions have is_active=false or is_cancelled=true');
      console.warn('[Schedule Service]   → Run testTeacherScheduleAccess() to diagnose');
    }

    // Step 2: Filter sessions where instructor_ids contains this instructor
    console.log(
      `[Schedule Service] STEP 2: Filtering sessions where instructor_ids contains: ${instructorId.substring(0, 8)}...`
    );
    const filteredSessions = (sessions || []).filter((session: any) =>
      session.instructor_ids && Array.isArray(session.instructor_ids) && session.instructor_ids.includes(instructorId)
    );

    console.log(
      `[Schedule Service]   ✓ Filter result: ${filteredSessions.length} sessions assigned to this instructor`
    );
    if (filteredSessions.length > 0) {
      console.log(
        `[Schedule Service]   Sample sessions (first 2): ${JSON.stringify(
          filteredSessions.slice(0, 2).map((s: any) => ({
            id: s.id,
            course: s.courses?.name,
            code: s.courses?.code,
            date: s.session_date,
            time: `${s.start_time} - ${s.end_time}`,
            room: s.rooms?.room_name || s.rooms?.room_number,
            building: s.rooms?.building?.name,
            status: s.session_status,
            instructorCount: s.instructor_ids?.length || 0,
          })),
          null,
          2
        )}`
      );
    } else {
      console.warn(
        `[Schedule Service]   ⚠️  NO SESSIONS FOUND - Instructor may not have any assigned lecture sessions`
      );
    }

    // Step 3: Fetch instructor names for instructor_ids array
    console.log('[Schedule Service] STEP 3: Enriching sessions with instructor details...');
    const extendedSessions = await Promise.all(
      filteredSessions.map(async (session: any, idx: number) => {
        let instructors: Array<{ id: string; name: string }> | undefined;

        if (session.instructor_ids && session.instructor_ids.length > 0) {
          if (idx === 0) {
            console.log(
              `[Schedule Service]   Fetching instructor names for ${session.instructor_ids.length} instructors...`
            );
          }
          const { data: instructorData, error: instructorError } = await supabase
            .from('instructors')
            .select('id, name')
            .in('id', session.instructor_ids);

          if (instructorError) {
            console.warn(
              `[Schedule Service] Error fetching instructors for session ${session.id}:`,
              instructorError
            );
          }

          instructors = instructorData || [];
        }

        const extendedSession = {
          ...session,
          instructors,
          course: session.courses,
          room: session.rooms,
          displayStatus: calculateSessionDisplayStatus(session),
        };

        return extendedSession;
      })
    );

    console.log(`[Schedule Service] ✓ Retrieved ${extendedSessions.length} sessions with displayStatus`);

    // Cache the result
    scheduleCache.set(cacheKey, {
      data: extendedSessions as LectureSessionExtended[],
      timestamp: Date.now(),
    });

    return { sessions: extendedSessions as LectureSessionExtended[], error: null };
  } catch (error) {
    console.error('[Schedule Service] ✗ Error fetching teacher schedule:', error);
    console.log(
      `[Schedule Service] ========================================`
    );
    return { sessions: null, error: error as Error };
  }
}

/**
 * Get TOTP session for a lecture session
 * @param lectureSessionId - Lecture session ID
 */
export async function getTOTPSession(
  lectureSessionId: string
): Promise<{ session: TOTPSession | null; error: Error | null }> {
  try {
    const { data, error } = await supabase
      .from('totp_sessions')
      .select('*')
      .eq('lecture_session_id', lectureSessionId)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    if (error && error.code !== 'PGRST116') {
      throw error;
    }

    return { session: data as TOTPSession | null, error: null };
  } catch (error) {
    console.error('Error fetching TOTP session:', error);
    return { session: null, error: error as Error };
  }
}

/**
 * Subscribe to real-time updates for a lecture session's TOTP code
 * @param lectureSessionId - Lecture session ID
 * @param onUpdate - Callback when TOTP code updates
 */
export function subscribeTOTPUpdates(
  lectureSessionId: string,
  onUpdate: (session: TOTPSession) => void
) {
  const channel = supabase
    .channel(`totp-session-${lectureSessionId}`)
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
        table: 'totp_sessions',
        filter: `lecture_session_id=eq.${lectureSessionId}`,
      },
      (payload) => {
        onUpdate(payload.new as TOTPSession);
      }
    )
    .subscribe();

  return channel;
}

/**
 * Helper: Format time from HH:mm:ss to HH:mm AM/PM
 */
export function formatTime(timeString: string | null): string {
  if (!timeString) return '';

  const [hours, minutes] = timeString.split(':');
  const hour = parseInt(hours, 10);
  const minute = minutes;
  const period = hour >= 12 ? 'PM' : 'AM';
  const formattedHour = hour % 12 || 12;

  return `${formattedHour}:${minute} ${period}`;
}

/**
 * Helper: Calculate duration in minutes from start and end times
 */
export function calculateDuration(startTime: string, endTime: string): number {
  const [startHour, startMin] = startTime.split(':').map(Number);
  const [endHour, endMin] = endTime.split(':').map(Number);

  const startMinutes = startHour * 60 + startMin;
  const endMinutes = endHour * 60 + endMin;

  return endMinutes - startMinutes;
}

/**
 * Helper: Get session status badge color
 */
export function getStatusColor(status: string, colors: any): string {
  switch (status) {
    case 'scheduled':
      return colors.primary;
    case 'active':
      return colors.success;
    case 'completed':
      return colors.textSecondary;
    case 'cancelled':
      return colors.danger;
    case 'rescheduled':
      return colors.warning;
    default:
      return colors.textSecondary;
  }
}

/**
 * Helper: Get session status label
 */
export function getStatusLabel(status: string): string {
  switch (status) {
    case 'scheduled':
      return 'Upcoming';
    case 'active':
      return 'Ongoing';
    case 'completed':
      return 'Completed';
    case 'cancelled':
      return 'Cancelled';
    case 'rescheduled':
      return 'Rescheduled';
    default:
      return status;
  }
}
/**
 * DIAGNOSTIC FUNCTION: Test teacher schedule access
 * Use this to debug why teacher schedule returns 0 sessions
 * Call from console: testTeacherScheduleAccess('userId', 'universityId')
 */
export async function testTeacherScheduleAccess(
  userId: string,
  universityId: string
): Promise<void> {
  console.log(`\n${'='.repeat(80)}`);
  console.log('🧪 TEACHER SCHEDULE ACCESS DIAGNOSTIC TEST');
  console.log(`${'='.repeat(80)}\n`);

  try {
    // Step 1: Get instructor data
    console.log('📍 STEP 1: Fetching instructor data...');
    const { data: instructors, error: instError } = await supabase
      .from('instructors')
      .select('id, code, name, user_id, is_active')
      .eq('user_id', userId);

    if (instError) {
      console.error('❌ Error fetching instructors:', instError);
      return;
    }

    console.log(`✅ Found ${instructors?.length || 0} instructor(s)`);
    if (!instructors?.[0]) {
      console.warn('⚠️ WARNING: No instructor record found for this user');
      console.log('   → User may not be linked to instructors table');
      return;
    }

    const instructor = instructors[0];
    const instructorId = instructor.id;
    console.log(`   Instructor: ${instructor.name} (${instructor.code})`);
    console.log(`   Instructor ID: ${instructorId}`);
    console.log(`   User ID: ${instructor.user_id}`);
    console.log(`   Active: ${instructor.is_active}\n`);

    // Step 2: Check what auth.uid() actually returns
    console.log('📍 STEP 2: Checking Supabase auth state...');
    const { data: authUser } = await supabase.auth.getUser();
    if (authUser?.user) {
      console.log(`✅ Auth user ID: ${authUser.user.id}`);
      console.log(`   Email: ${authUser.user.email}`);
      console.log(`   Match with instructor.user_id: ${authUser.user.id === instructor.user_id}\n`);
    } else {
      console.warn('⚠️ No authenticated user found\n');
    }

    // Step 3: Test basic lecture_sessions query
    console.log('📍 STEP 3: Testing basic lecture_sessions query...');
    const { data: allSessions, error: queryError } = await supabase
      .from('lecture_sessions')
      .select('id, course_id, session_date, instructor_ids')
      .eq('university_id', universityId)
      .eq('is_active', true)
      .eq('is_cancelled', false)
      .gte('session_date', '2026-01-28')
      .lte('session_date', '2026-05-28')
      .limit(10);

    if (queryError) {
      console.error('❌ Query error:', queryError);
      console.log('   → This indicates a database/RLS issue');
      console.log('   → Details:', {
        code: queryError.code,
        message: queryError.message,
        hint: queryError.hint,
      });
      return;
    }

    console.log(`✅ Query returned ${allSessions?.length || 0} sessions`);
    
    if (!allSessions || allSessions.length === 0) {
      console.error('❌ PROBLEM IDENTIFIED: Query returned 0 sessions!');
      console.log('   Likely causes:');
      console.log('   1. 🔒 RLS policy blocks read access');
      console.log('   2. 📊 No sessions exist for this university/date range');
      console.log('   3. ❌ Session filters exclude all data\n');
      
      // Test without date filters
      console.log('📍 STEP 3b: Testing without date filters...');
      const { data: allSessionsNoFilter } = await supabase
        .from('lecture_sessions')
        .select('id, course_id, session_date, instructor_ids')
        .eq('university_id', universityId)
        .limit(5);

      if (allSessionsNoFilter && allSessionsNoFilter.length > 0) {
        console.log(`⚠️ Found ${allSessionsNoFilter.length} sessions without date filters`);
        console.log('   → Date range might be wrong');
        console.log('   → Sample dates:', allSessionsNoFilter.map(s => s.session_date).slice(0, 3));
      }
      return;
    }

    console.log(`   Sample session: ID=${allSessions[0].id}`);
    console.log(`   Instructor IDs type: ${typeof allSessions[0].instructor_ids}`);
    console.log(`   Instructor IDs: ${JSON.stringify(allSessions[0].instructor_ids)}`);
    console.log(`   Is UUID in array: ${
      allSessions[0].instructor_ids && allSessions[0].instructor_ids.includes(instructorId)
        ? '✅ YES'
        : '❌ NO'
    }\n`);

    // Step 4: Check if this instructor is in any session
    console.log('📍 STEP 4: Checking if instructor is assigned to any sessions...');
    const sessionsForThisInstructor = allSessions.filter(s =>
      s.instructor_ids && Array.isArray(s.instructor_ids) && s.instructor_ids.includes(instructorId)
    );

    console.log(`✅ Found ${sessionsForThisInstructor.length} sessions for this instructor out of ${allSessions.length}`);

    if (sessionsForThisInstructor.length === 0) {
      console.warn('⚠️ Instructor not assigned to any returned sessions');
      console.log('   → Check database: is instructor_ids populated correctly?');
      console.log('   → Sample returned session instructor_ids:', allSessions[0].instructor_ids);
      console.log('   → Your instructor ID:', instructorId);
      return;
    }

    console.log(`   Assignment percentage: ${(sessionsForThisInstructor.length / allSessions.length * 100).toFixed(1)}%\n`);

    // Step 5: Full range test with all conditions
    console.log('📍 STEP 5: Testing complete query with all filters...');
    const startDate = '2026-01-28';
    const endDate = '2026-05-28';
    const { data: fullRangeSessions, error: fullError, status } = await supabase
      .from('lecture_sessions')
      .select('id, course_id, session_date')
      .eq('university_id', universityId)
      .eq('is_active', true)
      .eq('is_cancelled', false)
      .gte('session_date', startDate)
      .lte('session_date', endDate);

    if (fullError) {
      console.error('❌ Full range query error:', fullError);
      console.log('   Status:', status);
    } else {
      console.log(`✅ Full range query: ${fullRangeSessions?.length || 0} sessions`);
      console.log(`   Date range: ${startDate} to ${endDate}\n`);
    }

    // Final assessment
    console.log('=' .repeat(80));
    console.log('📊 DIAGNOSTIC SUMMARY:');
    console.log('=' .repeat(80));
    
    if (allSessions.length === 0) {
      console.error('❌ ROOT CAUSE: RLS Policy Issue or No Data');
      console.error('   The query is returning 0 sessions');
      console.log('\n🔧 NEXT STEPS:');
      console.log('   1. Check if RLS policy fix V2 was applied');
      console.log('   2. Verify instructor.user_id = auth.uid()');
      console.log('   3. Run: testTeacherScheduleAccess() again');
      console.log('   4. Check Supabase logs for RLS errors');
    } else if (sessionsForThisInstructor.length > 0) {
      console.log('✅ SUCCESS: Everything is working!');
      console.log(`   ${sessionsForThisInstructor.length} sessions found for instructor`);
      console.log('   Teacher schedule should display correctly');
      console.log('   If screen is still empty:');
      console.log('     - Clear browser cache');
      console.log('     - Restart dev server (npm start -- -c)');
      console.log('     - Close and reopen app');
    } else {
      console.error('⚠️ ISSUE: Sessions exist but not assigned to this instructor');
      console.log('   instructor_ids in database might not contain teacher ID');
    }
    
    console.log(`\n${'='.repeat(80)}\n`);

  } catch (error) {
    console.error('❌ Unexpected error:', error);
  }
}