import supabase from '@/lib/supabase';

/**
 * Cache for schedule data
 */
interface CacheEntry {
  data: LectureSessionExtended[];
  timestamp: number;
}

const scheduleCache: Map<string, CacheEntry> = new Map();
const CACHE_DURATION = 5 * 60 * 1000; // 5 minutes

/**
 * Semester date cache
 */
interface SemesterDateEntry {
  startDate: string;
  endDate: string;
  timestamp: number;
}

const semesterDateCache: Map<string, SemesterDateEntry> = new Map();
const SEMESTER_CACHE_DURATION = 24 * 60 * 60 * 1000; // 24 hours

/**
 * Fetch semester start and end dates
 * @param semesterId - Semester ID
 * @returns Object with startDate and endDate (YYYY-MM-DD format) or null
 */
export async function getSemesterDates(
  semesterId: string
): Promise<{ startDate: string; endDate: string } | null> {
  try {
    // Check cache first
    const cached = semesterDateCache.get(semesterId);
    if (cached && Date.now() - cached.timestamp < SEMESTER_CACHE_DURATION) {
      console.log('[Schedule Service] ✓ Semester dates from cache');
      return { startDate: cached.startDate, endDate: cached.endDate };
    }

    console.log('[Schedule Service] 📚 Fetching semester dates for:', semesterId.substring(0, 8) + '...');
    
    const { data, error } = await supabase
      .from('semesters')
      .select('start_date, end_date')
      .eq('id', semesterId)
      .single();

    if (error) {
      console.error('[Schedule Service] Error fetching semester dates:', error);
      return null;
    }

    const result = {
      startDate: data.start_date,
      endDate: data.end_date,
    };

    // Cache the result
    semesterDateCache.set(semesterId, {
      ...result,
      timestamp: Date.now(),
    });

    console.log('[Schedule Service] ✓ Semester date range:', result.startDate, 'to', result.endDate);
    return result;
  } catch (error) {
    console.error('[Schedule Service] Exception in getSemesterDates:', error);
    return null;
  }
}

/**
 * Lecture Session from database
 */
export interface LectureSession {
  id: string;
  university_id: string;
  timetable_id: string | null;
  course_id: string;
  section_id: string;
  room_id: string | null;
  instructor_ids: string[];
  session_date: string; // YYYY-MM-DD
  scheduled_start_time: string | null; // HH:mm:ss
  scheduled_end_time: string | null; // HH:mm:ss
  start_time: string; // HH:mm:ss
  end_time: string; // HH:mm:ss
  actual_start_time: string | null; // HH:mm:ss
  actual_end_time: string | null; // HH:mm:ss
  totp_required: boolean;
  session_status: 'scheduled' | 'active' | 'completed' | 'cancelled' | 'rescheduled';
  is_special_class: boolean;
  max_late_minutes: number;
  attendance_open: boolean;
  attendance_close_time: string | null;
  is_active: boolean;
  is_cancelled: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Extended lecture session with course and room details
 */
export interface LectureSessionExtended extends LectureSession {
  course?: {
    id: string;
    code: string;
    name: string;
  };
  room?: {
    id: string;
    room_number: string;
    room_name: string;
    building?: {
      id: string;
      name?: string;
    };
  };
  instructors?: Array<{
    id: string;
    name: string;
  }>;
}

/**
 * TOTP Session data
 */
export interface TOTPSession {
  id: string;
  university_id: string;
  lecture_session_id: string;
  code: string;
  totp_mode: 'autogenerated_dynamic' | 'autogenerated_static' | 'manual';
  generated_at: string;
  expires_at: string;
  last_refresh_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Fetch lecture sessions for a student
 * Filters by: university_id → student enrollments → section_id → lecture sessions
 * @param studentId - Student user ID
 * @param universityId - University ID
 * @param startDate - Start date (YYYY-MM-DD)
 * @param endDate - End date (YYYY-MM-DD)
 */
export async function getStudentSchedule(
  studentId: string,
  universityId: string,
  startDate: string,
  endDate: string
): Promise<{ sessions: LectureSessionExtended[] | null; error: Error | null }> {
  try {
    // Check cache first
    const cacheKey = `${studentId}-${startDate}-${endDate}`;
    const cached = scheduleCache.get(cacheKey);
    if (cached && Date.now() - cached.timestamp < CACHE_DURATION) {
      console.log('[Schedule Service] ✓ Schedule data from cache');
      return { sessions: cached.data, error: null };
    }

    console.log(
      `[Schedule Service] ========================================`
    );
    console.log(
      `[Schedule Service] 🔍 QUERY PARAMETERS:`
    );
    console.log(
      `[Schedule Service]   - studentId: ${studentId}`
    );
    console.log(
      `[Schedule Service]   - universityId: ${universityId}`
    );
    console.log(
      `[Schedule Service]   - dateRange: ${startDate} to ${endDate}`
    );
    console.log(
      `[Schedule Service] ========================================`
    );

    // Step 1: Get student enrollments with section details
    console.log(
      `[Schedule Service] STEP 1: Querying student_enrollments...`
    );
    const { data: enrollments, error: enrollmentError } = await supabase
      .from('student_enrollments')
      .select('section_id, batch')
      .eq('user_id', studentId)
      .eq('university_id', universityId)
      .eq('is_active', true);

    if (enrollmentError) throw enrollmentError;

    console.log(
      `[Schedule Service]   ✓ Query result: Found ${enrollments?.length || 0} enrollments`
    );
    if (enrollments && enrollments.length > 0) {
      console.log(
        `[Schedule Service]   Sample enrollments (first 2): ${JSON.stringify(
          enrollments.slice(0, 2),
          null,
          2
        )}`
      );
    } else {
      console.warn(
        `[Schedule Service]   ⚠️  NO ENROLLMENTS FOUND - Student may not be enrolled in any sections`
      );
    }

    if (!enrollments || enrollments.length === 0) {
      console.warn('[Schedule Service] No active enrollments found for student');
      return { sessions: [] as LectureSessionExtended[], error: null };
    }

    const sectionIds = enrollments.map((e) => e.section_id);

    // Step 2: Get lecture sessions for those sections
    console.log(
      `[Schedule Service] STEP 2: Querying lecture_sessions for ${sectionIds.length} section(s)...`
    );
    console.log(
      `[Schedule Service]   sectionIds: [${sectionIds.map((id) => id.substring(0, 8)).join(', ')}...]`
    );
    const { data: sessions, error: sessionsError } = await supabase
      .from('lecture_sessions')
      .select(
        `
        id,
        university_id,
        timetable_id,
        course_id,
        section_id,
        room_id,
        instructor_ids,
        session_date,
        scheduled_start_time,
        scheduled_end_time,
        start_time,
        end_time,
        actual_start_time,
        actual_end_time,
        totp_required,
        session_status,
        is_special_class,
        max_late_minutes,
        attendance_open,
        attendance_close_time,
        is_active,
        is_cancelled,
        created_at,
        updated_at,
        courses(id, code, name),
        rooms(id, room_number, room_name, building:buildings(id, name))
      `
      )
      .in('section_id', sectionIds)
      .eq('university_id', universityId)
      .eq('is_active', true)
      .eq('is_cancelled', false)
      .gte('session_date', startDate)
      .lte('session_date', endDate)
      .order('session_date', { ascending: true })
      .order('start_time', { ascending: true });

    if (sessionsError) throw sessionsError;

    console.log(
      `[Schedule Service]   ✓ Query result: Found ${sessions?.length || 0} lecture sessions`
    );
    if (sessions && sessions.length > 0) {
      console.log(
        `[Schedule Service]   Sample sessions (first 2): ${JSON.stringify(
          sessions.slice(0, 2).map((s: any) => ({
            id: s.id,
            course: s.courses?.name,
            code: s.courses?.code,
            date: s.session_date,
            time: `${s.start_time} - ${s.end_time}`,
            room: s.rooms?.room_name || s.rooms?.room_number,
            building: s.rooms?.building?.name,
            status: s.session_status,
            instructorIds: s.instructor_ids?.length || 0,
          })),
          null,
          2
        )}`
      );
    } else {
      console.warn(
        `[Schedule Service]   ⚠️  NO SESSIONS FOUND - Check if sections have lecture_sessions in the database for the date range`
      );
    }

    // Step 3: Fetch instructor names for instructor_ids array
    console.log('[Schedule Service] STEP 3: Enriching sessions with instructor details...');
    const extendedSessions = await Promise.all(
      (sessions || []).map(async (session: any, idx: number) => {
        let instructors: Array<{ id: string; name: string }> | undefined;

        if (session.instructor_ids && session.instructor_ids.length > 0) {
          if (idx === 0) {
            console.log(
              `[Schedule Service]   Fetching instructors for sessions...`
            );
          }
          const { data: instructorData, error: instructorError } = await supabase
            .from('instructors')
            .select('id, name')
            .in('id', session.instructor_ids);

          if (instructorError) {
            console.warn(
              `[Schedule Service] Error fetching instructors for session ${session.id}:`,
              instructorError
            );
          }

          instructors = instructorData || [];
        }

        const extendedSession = {
          ...session,
          instructors,
          course: session.courses,
          room: session.rooms,
        };

        return extendedSession;
      })
    );

    console.log(`[Schedule Service]   ✓ Enrichment complete`);
    console.log(`[Schedule Service] ✓ Successfully retrieved ${extendedSessions.length} sessions`);
    console.log(
      `[Schedule Service] ========================================`
    );

    // Cache the result
    scheduleCache.set(cacheKey, {
      data: extendedSessions as LectureSessionExtended[],
      timestamp: Date.now(),
    });

    return { sessions: extendedSessions as LectureSessionExtended[], error: null };
  } catch (error) {
    console.error('[Schedule Service] ❌ Error fetching student schedule:', error);
    console.log(
      `[Schedule Service] ========================================`
    );
    return { sessions: null, error: error as Error };
  }
}

/**
 * Fetch lecture sessions for a teacher
 * Filters by: instructor_ids array contains instructorId
 * @param instructorId - Instructor ID
 * @param universityId - University ID
 * @param startDate - Start date (YYYY-MM-DD)
 * @param endDate - End date (YYYY-MM-DD)
 */
export async function getTeacherSchedule(
  instructorId: string,
  universityId: string,
  startDate: string,
  endDate: string
): Promise<{ sessions: LectureSessionExtended[] | null; error: Error | null }> {
  try {
    console.log(`[Schedule Service] Fetching teacher schedule for: ${instructorId.substring(0, 8)}...`);
    console.log(`[Schedule Service] University: ${universityId.substring(0, 8)}...`);
    console.log(`[Schedule Service] Date range: ${startDate} to ${endDate}`);

    // Get lecture sessions where instructor_ids contains this instructor
    const { data: sessions, error: sessionsError } = await supabase
      .from('lecture_sessions')
      .select(
        `
        id,
        university_id,
        timetable_id,
        course_id,
        section_id,
        room_id,
        instructor_ids,
        session_date,
        scheduled_start_time,
        scheduled_end_time,
        start_time,
        end_time,
        actual_start_time,
        actual_end_time,
        totp_required,
        session_status,
        is_special_class,
        max_late_minutes,
        attendance_open,
        attendance_close_time,
        is_active,
        is_cancelled,
        created_at,
        updated_at,
        courses(id, code, name),
        rooms(id, room_number, room_name, building:buildings(id, name))
      `
      )
      .eq('university_id', universityId)
      .eq('is_active', true)
      .eq('is_cancelled', false)
      .gte('session_date', startDate)
      .lte('session_date', endDate)
      .order('session_date', { ascending: true })
      .order('start_time', { ascending: true });

    if (sessionsError) throw sessionsError;

    console.log(`[Schedule Service] Retrieved ${sessions?.length || 0} total lecture sessions`);

    // Filter sessions where instructor_ids contains this instructor
    const filteredSessions = (sessions || []).filter((session: any) =>
      session.instructor_ids && session.instructor_ids.includes(instructorId)
    );

    console.log(
      `[Schedule Service] After filtering by instructor: ${filteredSessions.length} sessions`
    );
    if (filteredSessions.length > 0) {
      console.log(
        `[Schedule Service] Sample sessions (first 2): ${JSON.stringify(
          filteredSessions.slice(0, 2).map((s: any) => ({
            course: s.courses?.name,
            date: s.session_date,
            time: s.start_time,
            status: s.session_status,
          })),
          null,
          2
        )}`
      );
    }

    // Fetch instructor names for instructor_ids array
    const extendedSessions = await Promise.all(
      filteredSessions.map(async (session: any) => {
        let instructors: Array<{ id: string; name: string }> | undefined;

        if (session.instructor_ids && session.instructor_ids.length > 0) {
          const { data: instructorData } = await supabase
            .from('instructors')
            .select('id, name')
            .in('id', session.instructor_ids);

          instructors = instructorData || [];
        }

        return {
          ...session,
          instructors,
          course: session.courses,
          room: session.rooms,
        };
      })
    );

    console.log(`[Schedule Service] ✓ Successfully retrieved ${extendedSessions.length} sessions`);
    return { sessions: extendedSessions as LectureSessionExtended[], error: null };
  } catch (error) {
    console.error('[Schedule Service] ✗ Error fetching teacher schedule:', error);
    return { sessions: null, error: error as Error };
  }
}

/**
 * Get TOTP session for a lecture session
 * @param lectureSessionId - Lecture session ID
 */
export async function getTOTPSession(
  lectureSessionId: string
): Promise<{ session: TOTPSession | null; error: Error | null }> {
  try {
    const { data, error } = await supabase
      .from('totp_sessions')
      .select('*')
      .eq('lecture_session_id', lectureSessionId)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    if (error && error.code !== 'PGRST116') {
      throw error;
    }

    return { session: data as TOTPSession | null, error: null };
  } catch (error) {
    console.error('Error fetching TOTP session:', error);
    return { session: null, error: error as Error };
  }
}

/**
 * Subscribe to real-time updates for a lecture session's TOTP code
 * @param lectureSessionId - Lecture session ID
 * @param onUpdate - Callback when TOTP code updates
 */
export function subscribeTOTPUpdates(
  lectureSessionId: string,
  onUpdate: (session: TOTPSession) => void
) {
  const channel = supabase
    .channel(`totp-session-${lectureSessionId}`)
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
        table: 'totp_sessions',
        filter: `lecture_session_id=eq.${lectureSessionId}`,
      },
      (payload) => {
        onUpdate(payload.new as TOTPSession);
      }
    )
    .subscribe();

  return channel;
}

/**
 * Helper: Format time from HH:mm:ss to HH:mm AM/PM
 */
export function formatTime(timeString: string | null): string {
  if (!timeString) return '';

  const [hours, minutes] = timeString.split(':');
  const hour = parseInt(hours, 10);
  const minute = minutes;
  const period = hour >= 12 ? 'PM' : 'AM';
  const formattedHour = hour % 12 || 12;

  return `${formattedHour}:${minute} ${period}`;
}

/**
 * Helper: Calculate duration in minutes from start and end times
 */
export function calculateDuration(startTime: string, endTime: string): number {
  const [startHour, startMin] = startTime.split(':').map(Number);
  const [endHour, endMin] = endTime.split(':').map(Number);

  const startMinutes = startHour * 60 + startMin;
  const endMinutes = endHour * 60 + endMin;

  return endMinutes - startMinutes;
}

/**
 * Helper: Get session status badge color
 */
export function getStatusColor(status: string, colors: any): string {
  switch (status) {
    case 'scheduled':
      return colors.primary;
    case 'active':
      return colors.success;
    case 'completed':
      return colors.textSecondary;
    case 'cancelled':
      return colors.danger;
    case 'rescheduled':
      return colors.warning;
    default:
      return colors.textSecondary;
  }
}

/**
 * Helper: Get session status label
 */
export function getStatusLabel(status: string): string {
  switch (status) {
    case 'scheduled':
      return 'Upcoming';
    case 'active':
      return 'Ongoing';
    case 'completed':
      return 'Completed';
    case 'cancelled':
      return 'Cancelled';
    case 'rescheduled':
      return 'Rescheduled';
    default:
      return status;
  }
}
